#pragma once

#include "engine/Time.hpp"
#include "engine/assets/SfmlAssetManager.hpp"
#include "engine/ecs/EntityManager.hpp"
#include "engine/ecs/SystemManager.hpp"
#include "engine/graphics/Camera.hpp"
#include "engine/graphics/SfmlRenderer.hpp"
#include "engine/input/ActionMap.hpp"
#include "engine/input/ActionState.hpp"
#include "engine/input/Input.hpp"
#include "engine/systems/RenderSystem.hpp"

#include <SFML/Graphics/RenderWindow.hpp>
#include <SFML/Window/Event.hpp>

#include <cstddef>
#include <optional>

namespace engine
{

/// Owns the window and drives the main loop, and is the composition root for
/// the runtime.
///
/// ### What Application owns
///
/// | Member | Responsibility |
/// | ------ | -------------- |
/// | `sf::RenderWindow` | the window, its events, and presentation |
/// | `Time` | measures how long each frame actually took |
/// | `input::Input` | raw keyboard state for the current frame |
/// | `input::ActionMap` | which physical key drives which action |
/// | `input::ActionState` | what the actions are doing this frame |
/// | `EntityManager` | the world: every entity and its components |
/// | `SystemManager` | the simulation systems, run in registration order |
/// | `graphics::Camera` | where in the world the view is looking |
/// | `SfmlRenderer` | the graphics boundary; references the window |
/// | `assets::SfmlAssetManager` | every asset the configuration declares, loaded once |
/// | `RenderSystem` | draws the world through the renderer, using those assets |
///
/// Application is the only place these are wired together. It implements no
/// behaviour of its own: there is no physics, no gameplay and no drawing code
/// here, only ordering. The simulation systems themselves are registered by the
/// game, through `systemManager()`.
///
/// ### The asset manager, and where its path comes from
///
/// Assets are loaded once, by the constructor, from the path in
/// `config::kAssetsConfig` - a value generated by CMake from
/// `-DENGINE_ASSETS_CONFIG`. So the location is fixed at build time and never
/// depends on the process working directory; launching the game from anywhere
/// loads the same assets.
///
/// The tradeoff is worth naming rather than leaving to be discovered: an absolute
/// path baked into the binary means a build relocated to another machine still
/// expects the repository where it was configured. That is correct for developing
/// against this repository and wrong for a shipped game, which will need the
/// configuration found at runtime - beside the executable, or handed in by the
/// game. Nothing else in the engine guesses at a location, and nothing falls back
/// to the working directory if the configured path is wrong: the constructor
/// throws, so a missing or broken configuration is a startup failure with a
/// message rather than a game that quietly renders nothing.
///
/// ### The camera is a plain owned value
///
/// `graphics::Camera` is a value, not a component and not a singleton, exactly
/// like `Input` and `Time`. It is view state rather than world state: it
/// describes where the *player of the game* is looking, which is a property of
/// the program, not of any entity. Making it a component would mean inventing a
/// singleton entity to hold three numbers and would give every system a way to
/// reach the camera by querying, which is the coupling this design avoids.
///
/// Systems that need the camera are handed a reference to it. `RenderSystem`
/// takes a `const&` and can only read it; `CameraSystem` takes a `&` and drives
/// it. Neither owns it.
///
/// ### Window ownership
///
/// The window belongs to Application and nobody else. `SfmlRenderer` holds a
/// **reference** to it rather than owning it, and `RenderSystem` holds a
/// reference to the renderer. Ownership therefore runs in one direction only,
/// Application to window, with everything else borrowing. The window's
/// destructor still closes it, so shutdown is still plain RAII: no global
/// window, no static window, no singleton renderer, no global graphics context.
///
/// Member declaration order matters here: the window is declared first so it is
/// constructed first, and the renderer and render system bind to an already
/// constructed window. Destruction runs in reverse, so they go before the window
/// closes. The camera is declared before `RenderSystem` for the same reason.
///
/// ### The frame
///
/// ```text
/// input.beginFrame()                 clear pressed/released, keep held state
/// processEvents()                    window close, and keyboard into Input
/// time.tick()                        measures this frame's real duration
/// actions.update(map, input)         Input + ActionMap -> this frame's actions
/// systemManager.update(world, act, dt) simulation systems read actions, write data
///   ├─ MovementSystem                 input -> Transform::velocity
///   ├─ PhysicsSystem                  velocity -> position, then collisions
///   └─ CameraSystem                   target's world position -> Camera
/// entityManager.update()             deferred destruction cleanup
/// renderer.beginFrame()              RENDER: start the frame
/// renderer.clear(background)         RENDER: configured background colour
/// renderSystem.update(world, in, 0)  RENDER: world -> screen, submit draws
///   ├─ rectangles                     Transform + Rectangle, then draw
///   └─ textures                       Transform + Texture, name -> asset, draw
/// renderer.endFrame()                RENDER: present
/// ```
///
/// The event, update, render, display high-level order from Phase 1 is intact.
/// Systems run before cleanup, so an entity a system flagged this frame is
/// erased only once nothing is iterating.
///
/// The systems shown inside `systemManager.update` are registered by whoever
/// builds the game, not here: `Application` owns the loop and orders the pass,
/// but it does not decide what simulates. `PhysicsSystem` must be registered
/// after `MovementSystem`, and `CameraSystem` after both, because registration
/// order is update order and the camera should follow where the target ended up
/// this frame.
///
/// The camera is written during simulation and read during rendering. That is
/// the whole of its involvement in the frame: it changes what you see, never
/// what is simulated.
///
/// `input.beginFrame()` runs **before** `processEvents()` on purpose. It clears
/// only the frame-local transients, so clearing can never discard an event that
/// arrived this frame: a key pressed during `processEvents()` is still readable
/// by every system later in the same frame. Held state survives the clear.
///
/// `RenderSystem` is deliberately **not** registered in the `SystemManager`. It
/// is an ordinary `System` with the same interface and lifetime rules, but the
/// render pass has to be bracketed by `beginFrame()` and `endFrame()` and has to
/// run after every simulation system, so `Application` drives it in its own
/// pass. Folding it into the simulation list would mean either clearing mid
/// simulation or presenting before the last system ran. This is recorded in
/// [docs/rendering.md](docs/rendering.md).
class Application
{
public:
    /// Opens the game window using the settings from engine/EngineConfig.hpp.
    Application();

    /// Closes the window. sf::Window cleans itself up, so nothing else is needed.
    ~Application() = default;

    Application(const Application&) = delete;
    Application& operator=(const Application&) = delete;
    Application(Application&&) = delete;
    Application& operator=(Application&&) = delete;

    /// Runs the main loop until the window is closed and returns EXIT_SUCCESS.
    ///
    /// @param maxFrameCount Optional cap on the number of frames to run. The
    ///        automated smoke test uses it so the loop terminates on its own
    ///        instead of waiting for a user to close the window.
    int run(std::optional<std::size_t> maxFrameCount = std::nullopt);

    /// The world. Entities are added here by main(), by an example, or by a
    /// future scene, never by a system.
    [[nodiscard]] ecs::EntityManager& entityManager() noexcept { return m_entityManager; }

    /// The view onto the world.
    ///
    /// The camera is mutable because the game configures it, and a
    /// `CameraSystem` drives it. It is handed out by reference rather than
    /// const so the viewport can be set once the window size is known.
    [[nodiscard]] graphics::Camera& camera() noexcept { return m_camera; }

    /// The behaviour. Systems are registered here and run in the order they
    /// were added.
    [[nodiscard]] ecs::SystemManager& systemManager() noexcept { return m_systemManager; }

    /// Frame timing, mainly so a debug overlay could read it. Systems are handed
    /// the delta as a parameter and should not need this.
    [[nodiscard]] const Time& time() const noexcept { return m_time; }

    /// The graphics boundary, for a debug overlay or a tool. Systems should be
    /// handed an `engine::graphics::Renderer&` instead of reaching for this.
    [[nodiscard]] graphics::Renderer& renderer() noexcept { return m_renderer; }

    /// Raw keyboard state for the current frame.
    ///
    /// For a debug overlay or a tool that wants to show which keys are held.
    /// **Gameplay systems cannot reach this**: they are handed the action snapshot
    /// instead, and a system has no way to name a physical key. Keeping the raw
    /// layer reachable from the composition root and from nowhere else is what
    /// stops "just check if the key is down" from creeping back into a system.
    [[nodiscard]] const input::Input& input() const noexcept { return m_input; }

    /// Which physical key drives which action.
    ///
    /// Handed out as a const reference: the mapping is established once, at
    /// construction, and no system changes it. A rebinding feature would need a
    /// mutable accessor and would have to say what a mid-frame change means -
    /// which is why there is not one here.
    [[nodiscard]] const input::ActionMap& actionMap() const noexcept { return m_actionMap; }

    /// What the actions are doing this frame, as handed to every system.
    [[nodiscard]] const input::ActionState& actions() const noexcept { return m_actions; }

    /// The loaded assets, for a debug overlay or a tool.
    ///
    /// Handed out as the **interface**, by const reference, so a caller can look a
    /// resource up but cannot load, replace or remove one. The concrete manager is
    /// owned here and is not exposed: a game gets reads, not the ability to
    /// invalidate the references other systems are holding.
    [[nodiscard]] const assets::AssetManager& assets() const noexcept { return m_assets; }

private:
    void processEvents();
    void update();
    void render();

    // Declaration order is load bearing, and this is the one place in the engine
    // where getting it wrong is a use-after-free rather than a compile error.
    //
    // Construction runs in declaration order, so each borrower is declared after
    // what it binds to:
    //
    //   m_window       opened first
    //   m_camera       configured in the constructor body, before the render system
    //   m_renderer     binds to m_window
    //   m_assets       loads the configured files; depends on nothing here
    //   m_renderSystem binds to all three of the above
    //
    // Destruction runs in reverse, so `m_renderSystem` is destroyed **first**, and
    // therefore while the renderer, the camera and the asset manager are all still
    // alive. That is the guarantee that matters: a render pass must never be able
    // to reach a camera, a window or a texture that has already gone away. Adding
    // a member after `m_renderSystem` would be safe; adding one before it is not,
    // unless it is something `m_renderSystem` holds a reference to.
    sf::RenderWindow m_window;
    Time m_time;
    input::Input m_input;
    input::ActionMap m_actionMap;
    input::ActionState m_actions;
    ecs::EntityManager m_entityManager;
    ecs::SystemManager m_systemManager;
    graphics::Camera m_camera;
    graphics::SfmlRenderer m_renderer;
    assets::SfmlAssetManager m_assets;
    systems::RenderSystem m_renderSystem;
    bool m_isRunning = true;
};

} // namespace engine
