#pragma once

#include "engine/Time.hpp"
#include "engine/assets/SfmlAssetManager.hpp"
#include "engine/ecs/EntityManager.hpp"
#include "engine/ecs/SystemManager.hpp"
#include "engine/graphics/Camera.hpp"
#include "engine/graphics/SfmlRenderer.hpp"
#include "engine/input/ActionMap.hpp"
#include "engine/input/ActionState.hpp"
#include "engine/input/Input.hpp"
#include "engine/scene/Scene.hpp"
#include "engine/systems/RenderSystem.hpp"

#include <SFML/Graphics/RenderWindow.hpp>
#include <SFML/Window/Event.hpp>

#include <cstddef>
#include <functional>
#include <memory>
#include <optional>

namespace engine
{

/// Owns the window and drives the main loop, and is the composition root for
/// the runtime.
///
/// ### What Application owns
///
/// | Member | Responsibility |
/// | ------ | -------------- |
/// | `sf::RenderWindow` | the window, its events, and presentation |
/// | `Time` | measures how long each frame actually took |
/// | `input::Input` | raw keyboard state for the current frame |
/// | `input::ActionMap` | which physical key drives which action |
/// | `input::ActionState` | what the actions are doing this frame |
/// | `EntityManager` | the world: every entity and its components |
/// | `SystemManager` | the simulation systems, run in registration order |
/// | `graphics::Camera` | where in the world the view is looking |
/// | `SfmlRenderer` | the graphics boundary; references the window |
/// | `assets::SfmlAssetManager` | every asset the configuration declares, loaded once |
/// | `RenderSystem` | draws the world through the renderer, using those assets |
///
/// Application is the only place these are wired together. It implements no
/// behaviour of its own: there is no physics, no gameplay and no drawing code
/// here, only ordering. The simulation systems themselves are registered by the
/// game, through `systemManager()`.
///
/// ### The asset manager, and where its path comes from
///
/// Assets are loaded once, by the constructor, from the path in
/// `config::kAssetsConfig` - a value generated by CMake from
/// `-DENGINE_ASSETS_CONFIG`. So the location is fixed at build time and never
/// depends on the process working directory; launching the game from anywhere
/// loads the same assets.
///
/// The tradeoff is worth naming rather than leaving to be discovered: an absolute
/// path baked into the binary means a build relocated to another machine still
/// expects the repository where it was configured. That is correct for developing
/// against this repository and wrong for a shipped game, which will need the
/// configuration found at runtime - beside the executable, or handed in by the
/// game. Nothing else in the engine guesses at a location, and nothing falls back
/// to the working directory if the configured path is wrong: the constructor
/// throws, so a missing or broken configuration is a startup failure with a
/// message rather than a game that quietly renders nothing.
///
/// ### The camera is a plain owned value
///
/// `graphics::Camera` is a value, not a component and not a singleton, exactly
/// like `Input` and `Time`. It is view state rather than world state: it
/// describes where the *player of the game* is looking, which is a property of
/// the program, not of any entity. Making it a component would mean inventing a
/// singleton entity to hold three numbers and would give every system a way to
/// reach the camera by querying, which is the coupling this design avoids.
///
/// Systems that need the camera are handed a reference to it. `RenderSystem`
/// takes a `const&` and can only read it; `CameraSystem` takes a `&` and drives
/// it. Neither owns it.
///
/// ### Window ownership
///
/// The window belongs to Application and nobody else. `SfmlRenderer` holds a
/// **reference** to it rather than owning it, and `RenderSystem` holds a
/// reference to the renderer. Ownership therefore runs in one direction only,
/// Application to window, with everything else borrowing. The window's
/// destructor still closes it, so shutdown is still plain RAII: no global
/// window, no static window, no singleton renderer, no global graphics context.
///
/// Member declaration order matters here: the window is declared first so it is
/// constructed first, and the renderer and render system bind to an already
/// constructed window. Destruction runs in reverse, so they go before the window
/// closes. The camera is declared before `RenderSystem` for the same reason.
///
/// ### The frame
///
/// The frame has two shapes, and which one runs depends on one question: is a
/// scene active?
///
/// **With a scene.** A scene owns a world and the systems that run in it, so
/// `Application` does not have a world to update and does not know what
/// `update`/`render` mean for a menu. It hands the frame to the scene:
///
/// ```text
/// input.beginFrame()                 clear pressed/released, keep held state
/// processEvents()                    window close, and keyboard into Input
/// update():
///   time.tick()                      measure the frame that just happened
///   actions.update(actionMap, input)  one coherent snapshot, built once
///   applyPendingTransition()         THE FRAME BOUNDARY - see below
///   scene->update(actions, delta)    the scene's world, its systems
/// render():
///   renderer.beginFrame() / clear()
///   scene->render()                  the scene's world -> draws
///   renderer.endFrame()
/// ```
///
/// **Without a scene.** `Application` drives its own `entityManager()` and
/// `systemManager()` instead, exactly as it did before scenes existed. That is
/// what several tests do, and it is a real supported mode rather than a
/// leftover: a tool or a test can build a world without a game.
///
/// ### The frame boundary, and why a transition is deferred
///
/// A scene cannot replace itself. It records what it wants - `SceneTransition::to`,
/// `stay` or `quitApplication` - and `applyPendingTransition()` acts on it at the
/// start of the next frame, before the new scene is built and before any of the
/// outgoing scene's systems run again.
///
/// Both orderings matter, and they are the reason for the deferral:
///
/// - **Before any of the old scene's systems run again**, so a scene is never
///   destroyed while one of its own systems is still executing. `update()` calls
///   `applyPendingTransition()` *before* `scene->update()`, never inside it, so
///   the worst case is a scene that finishes a frame it is about to lose.
/// - **Destroy old before building new**, so two scenes never coexist and a
///   constructor that throws leaves no scene rather than a stale one.
///
/// The visible consequence is that a transition takes effect on the *next* frame,
/// so every frame belongs entirely to one scene - never updated by the old one and
/// drawn by the new one. That is stronger than the requirement and it is free:
/// nothing outside the loop can observe a half-transition frame, because a frame
/// is the unit the loop publishes.
///
/// A `quit` request is applied here too, and it skips the rest of the frame: the
/// scene that asked has finished updating, so there is nothing left worth drawing.
///
/// ### The frame, without a scene
///
/// ```text
/// input.beginFrame()                 clear pressed/released, keep held state
/// processEvents()                    window close, and keyboard into Input
/// time.tick()                        measures this frame's real duration
/// actions.update(map, input)         Input + ActionMap -> this frame's actions
/// systemManager.update(world, act, dt) simulation systems read actions, write data
///   ├─ MovementSystem                 input -> Transform::velocity
///   ├─ PhysicsSystem                  velocity -> position, then collisions
///   └─ CameraSystem                   target's world position -> Camera
/// entityManager.update()             deferred destruction cleanup
/// renderer.beginFrame()              RENDER: start the frame
/// renderer.clear(background)         RENDER: configured background colour
/// renderSystem.update(world, in, 0)  RENDER: world -> screen, submit draws
///   ├─ rectangles                     Transform + Rectangle, then draw
///   └─ textures                       Transform + Texture, name -> asset, draw
/// renderer.endFrame()                RENDER: present
/// ```
///
/// The event, update, render, display high-level order from Phase 1 is intact.
/// Systems run before cleanup, so an entity a system flagged this frame is
/// erased only once nothing is iterating.
///
/// The systems shown inside `systemManager.update` are registered by whoever
/// builds the game, not here: `Application` owns the loop and orders the pass,
/// but it does not decide what simulates. `PhysicsSystem` must be registered
/// after `MovementSystem`, and `CameraSystem` after both, because registration
/// order is update order and the camera should follow where the target ended up
/// this frame.
///
/// That decision is unchanged by scenes, and it is worth being explicit about
/// because a scene looks like it might be the place where the engine starts
/// registering systems. It is not. A scene *registers* systems for *its own*
/// world - [engine::scene::PlayScene] registers four - but the engine still
/// registers none of its own, and a scene is told what to register by nothing more
/// than its own constructor. The distinction is who decides: a scene decides
/// because it is the game, and `Application` does not decide at all.
///
/// The camera is written during simulation and read during rendering. That is
/// the whole of its involvement in the frame: it changes what you see, never
/// what is simulated.
///
/// `input.beginFrame()` runs **before** `processEvents()` on purpose. It clears
/// only the frame-local transients, so clearing can never discard an event that
/// arrived this frame: a key pressed during `processEvents()` is still readable
/// by every system later in the same frame. Held state survives the clear.
///
/// `RenderSystem` is deliberately **not** registered in the `SystemManager`. It
/// is an ordinary `System` with the same interface and lifetime rules, but the
/// render pass has to be bracketed by `beginFrame()` and `endFrame()` and has to
/// run after every simulation system, so `Application` drives it in its own
/// pass. Folding it into the simulation list would mean either clearing mid
/// simulation or presenting before the last system ran. This is recorded in
/// [docs/rendering.md](docs/rendering.md).
/// Builds a scene from the shared infrastructure.
///
/// The default is [engine::scene::makeScene]. It is a type rather than a hard call
/// so that a test can hand `Application` a scene it can watch being destroyed,
/// which is the only way to observe that a transition really releases the old one
/// rather than merely forgetting it. This is the same dependency inversion the
/// rest of the engine already uses - a system is handed a `graphics::Renderer&`,
/// [engine::level::LevelLoader] is handed an `assets::AssetManager&`, and both
/// have test fakes - applied to scene construction, which is the one piece of
/// `Application`'s work that is otherwise unreachable from a test.
using SceneFactory =
    std::function<std::unique_ptr<scene::Scene>(scene::SceneId, const scene::SceneContext&)>;

class Application
{
public:
    /// Opens the game window using the settings from engine/EngineConfig.hpp.
    Application();

    /// Closes the window. sf::Window cleans itself up, so nothing else is needed.
    ~Application() = default;

    Application(const Application&) = delete;
    Application& operator=(const Application&) = delete;
    Application(Application&&) = delete;
    Application& operator=(Application&&) = delete;

    /// Runs the main loop until the window is closed and returns EXIT_SUCCESS.
    ///
    /// @param maxFrameCount Optional cap on the number of frames to run. The
    ///        automated smoke test uses it so the loop terminates on its own
    ///        instead of waiting for a user to close the window.
    int run(std::optional<std::size_t> maxFrameCount = std::nullopt);

    /// Runs the main loop, driving the keyboard from a recorded script.
    ///
    /// A single deliberately small seam, and it exists because of one question this
    /// engine otherwise cannot answer at all: *"does the whole chain work in the
    /// shipped executable, and not only in a test binary?"* Everything up to and
    /// including the window, the asset manager, the scene factory, the systems and
    /// the renderer is production; the only thing replaced is **which key the window
    /// reports**, and even that goes in through the real [engine::input::Input] state
    /// machine rather than round the back of it.
    ///
    /// ### The script
    ///
    /// ```text
    /// P        press and release P on this frame
    /// D:120    hold D down for the next 120 frames
    /// .:30     advance 30 frames with nothing pressed
    /// ```
    ///
    /// A token applies to the frame it is read on. `D:120` presses on this frame and
    /// releases on the 120th, so 120 frames really are held.
    ///
    /// ### Why it is on Application and not on Input
    ///
    /// [engine::input::Input] is the window's view of the keyboard and knows nothing
    /// about where a frame came from. This is a **composition-root** decision - what
    /// the process pretends the player is doing - so it belongs beside `--frames` in
    /// `main`, with the result handed to the owner. No system can reach it, no
    /// gameplay behaviour changes, and a game that never asks for it pays nothing
    /// beyond a string comparison per frame.
    ///
    /// @param script The tokens described above. Empty is the ordinary case.
    int runWithInput(std::string_view script, std::optional<std::size_t> maxFrameCount = std::nullopt);

    /// The world. Entities are added here by main(), by an example, or by a
    /// future scene, never by a system.
    [[nodiscard]] ecs::EntityManager& entityManager() noexcept { return m_entityManager; }

    /// The view onto the world.
    ///
    /// The camera is mutable because the game configures it, and a
    /// `CameraSystem` drives it. It is handed out by reference rather than
    /// const so the viewport can be set once the window size is known.
    [[nodiscard]] graphics::Camera& camera() noexcept { return m_camera; }

    /// The behaviour. Systems are registered here and run in the order they
    /// were added.
    [[nodiscard]] ecs::SystemManager& systemManager() noexcept { return m_systemManager; }

    /// Frame timing, mainly so a debug overlay could read it. Systems are handed
    /// the delta as a parameter and should not need this.
    [[nodiscard]] const Time& time() const noexcept { return m_time; }

    /// The graphics boundary, for a debug overlay or a tool. Systems should be
    /// handed an `engine::graphics::Renderer&` instead of reaching for this.
    [[nodiscard]] graphics::Renderer& renderer() noexcept { return m_renderer; }

    /// Raw keyboard state for the current frame.
    ///
    /// For a debug overlay or a tool that wants to show which keys are held.
    /// **Gameplay systems cannot reach this**: they are handed the action snapshot
    /// instead, and a system has no way to name a physical key. Keeping the raw
    /// layer reachable from the composition root and from nowhere else is what
    /// stops "just check if the key is down" from creeping back into a system.
    [[nodiscard]] const input::Input& input() const noexcept { return m_input; }

    /// Which physical key drives which action.
    ///
    /// Handed out as a const reference: the mapping is established once, at
    /// construction, and no system changes it. A rebinding feature would need a
    /// mutable accessor and would have to say what a mid-frame change means -
    /// which is why there is not one here.
    [[nodiscard]] const input::ActionMap& actionMap() const noexcept { return m_actionMap; }

    /// What the actions are doing this frame, as handed to every system.
    [[nodiscard]] const input::ActionState& actions() const noexcept { return m_actions; }

    /// The loaded assets, for a debug overlay or a tool.
    ///
    /// Handed out as the **interface**, by const reference, so a caller can look a
    /// resource up but cannot load, replace or remove one. The concrete manager is
    /// owned here and is not exposed: a game gets reads, not the ability to
    /// invalidate the references other systems are holding.
    [[nodiscard]] const assets::AssetManager& assets() const noexcept { return m_assets; }

    /// Asks for `id` to become the active scene.
    ///
    /// ### Deferred, always
    ///
    /// The request is recorded, not performed, and is applied by
    /// [applyPendingTransition] at the start of the next frame - so the scene that
    /// is active during the current frame finishes its update and its render first.
    /// There is no "apply it now" path, because a scene asking to be replaced from
    /// inside its own update is the case that has to be safe, and one rule that is
    /// always deferred has no case where it is not.
    ///
    /// A call made before the first frame therefore takes effect at the start of
    /// that frame, which is what `main` relies on: it asks for the menu and then
    /// runs, and the first frame is already the menu's.
    ///
    /// Building the new scene runs the new scene's constructor, which for
    /// [scene::PlayScene] reads the level. A level that fails to load throws out of
    /// this method *and* out of the next [update], with the old scene already gone:
    /// a transition that failed is not a transition that was rolled back.
    void changeScene(const scene::SceneId id);

    /// Which scene is active, or `nullopt` if no scene is driving the frame.
    ///
    /// `nullopt` is a real state, not an error: an `Application` with no scene
    /// drives its own [entityManager] and [systemManager] instead, which is how
    /// this engine was used before scenes existed and is still how several tests
    /// build a world without a window-level game.
    [[nodiscard]] std::optional<scene::SceneId> sceneId() const noexcept;

    /// The active scene, or `nullptr` if there is none.
    ///
    /// A borrowed pointer into the owned scene, valid until the next transition or
    /// until this `Application` is destroyed. Held for tests and diagnostics; the
    /// frame is driven through [update] and [render] rather than through this.
    [[nodiscard]] const scene::Scene* currentScene() const noexcept;

    /// Whether the main loop should keep going.
    ///
    /// Cleared by a window close, by [run]'s frame cap being reached, and by a
    /// scene's [scene::SceneTransition::quitApplication] at the next frame boundary.
    ///
    /// Public because "did the quit request take effect" has no other observable
    /// answer. The alternative test is to call [run] with no frame cap and see
    /// whether it returns, which means a failing assertion becomes a **hang** - a
    /// timeout rather than a failure, and a suite that takes the whole run down
    /// with it. Asking is one call and it says exactly what happened.
    [[nodiscard]] bool isRunning() const noexcept { return m_isRunning; }

    /// Replaces the factory used to build scenes. For tests.
    ///
    /// The default is [engine::scene::makeScene]. Replacing it does not rebuild the
    /// current scene: a scene already active stays until a transition asks for
    /// another one, because swapping the builder under a live scene would change
    /// what "the current scene" means half way through a game.
    void setSceneFactory(SceneFactory factory);

    /// Advances one frame: timing, actions, the transition boundary, then behaviour.
    ///
    /// Public so a test can step a frame at a time and observe the scene boundary
    /// from the outside. The alternative - a loop that only exists inside [run] -
    /// would make "the transition is applied between frames" untestable, because
    /// there would be no way to be *between* two frames.
    void update();

    /// Draws one frame through the active scene, or through [m_renderSystem] when
    /// there is no scene.
    ///
    /// Public for the same reason as [update], and for the stronger one: a test can
    /// run [update] and [render] separately and prove that a frame is never half
    /// one scene and half another.
    void render();

private:
    void processEvents();

    /// Feeds the recorded keyboard script into [m_input] for this frame. A no-op
    /// when [runWithInput] was never used. See [runWithInput].
    void applyRecordedInput();

    /// Applies a transition request, if one is pending. The frame boundary.
    void applyPendingTransition();

    // Declaration order is load bearing, and this is the one place in the engine
    // where getting it wrong is a use-after-free rather than a compile error.
    //
    // Construction runs in declaration order, so each borrower is declared after
    // what it binds to:
    //
    //   m_window       opened first
    //   m_camera       configured in the constructor body, before the render system
    //   m_renderer     binds to m_window
    //   m_assets       loads the configured files; depends on nothing here
    //   m_renderSystem binds to all three of the above
    //
    // Destruction runs in reverse, so `m_renderSystem` is destroyed **first**, and
    // therefore while the renderer, the camera and the asset manager are all still
    // alive. That is the guarantee that matters: a render pass must never be able
    // to reach a camera, a window or a texture that has already gone away. Adding
    // a member after `m_renderSystem` would be safe; adding one before it is not,
    // unless it is something `m_renderSystem` holds a reference to.
    sf::RenderWindow m_window;
    Time m_time;
    input::Input m_input;
    input::ActionMap m_actionMap;
    input::ActionState m_actions;
    ecs::EntityManager m_entityManager;
    ecs::SystemManager m_systemManager;
    graphics::Camera m_camera;
    graphics::SfmlRenderer m_renderer;
    assets::SfmlAssetManager m_assets;
    systems::RenderSystem m_renderSystem;

    // Declared after everything it borrows and before everything that borrows it,
    // so the file reads in the order the pointers are valid in:
    //
    //   m_sceneContext   holds pointers to m_renderer, m_camera and m_assets
    //   m_scene          holds a pointer to m_sceneContext, plus the scene's world
    //   m_sceneFactory   builds the next m_scene
    //
    // `m_sceneContext` has no destructor logic, so none of these could actually
    // dangle whatever the order. They are in this order so that a reader does not
    // have to work that out.
    scene::SceneContext m_sceneContext;

    /// The active scene, or `nullptr`.
    ///
    /// A `unique_ptr` and not a `shared_ptr` in a map of live scenes, which is what
    /// the course reference uses. A map keeps *every* scene alive for the life of
    /// the process, so returning to the menu would find the old menu, with the old
    /// menu's selection and the old menu's entities, still there - and the "old
    /// scene is destroyed on transition" guarantee would be a promise the code did
    /// not keep. One owner, one scene, destroyed on replacement: the lifetime is
    /// deterministic, which is the property that makes a scene's raw pointers into
    /// its own world and systems safe.
    std::unique_ptr<scene::Scene> m_scene;

    /// The request the active scene made, applied at the next frame boundary.
    ///
    /// A whole [scene::SceneTransition] rather than a bare id, because "stop the
    /// application" is a legitimate outcome that is not a scene and must not have
    /// to be expressed as one.
    std::optional<scene::SceneTransition> m_pendingTransition;

    SceneFactory m_sceneFactory;

    /// The recorded keyboard script, or empty. See [runWithInput].
    std::string m_inputScript;

    bool m_isRunning = true;
};

} // namespace engine
