/// The game executable.
///
/// ### What this file is for now
///
/// This used to be where the world was built: it opened the level file, converted
/// the grid, spawned every entity and registered four systems, in about a hundred
/// and fifty lines of heavily documented code. All of that now lives in
/// [engine::scene::PlayScene], where it belongs, and what is left here is the
/// composition root: make the application, say which scene to start in, run it.
///
/// That is the whole of the change, and it is worth being precise about *why* it
/// is a change rather than a tidy-up. Before scenes, `main` had to know how to
/// build a level, because the frame loop had no idea what a level was: the loop
/// drove `Application`'s own world and `main` had filled it. Giving the loop a
/// scene to drive means the loop asks "what is happening" instead of "what exists",
/// and every answer to the first question now lives in a scene rather than in the
/// entry point. Adding a Pause or a Win state later is a new scene, not a new
/// branch in `main`.
///
/// ### What `main` deliberately does not do
///
/// - It does not build a world, register a system or add a component. [engine::Application]
///   does not need to be told, and the world-building code that used to be here is
///   what a scene's constructor is for.
/// - It does not read a key. The game starts in a menu, and the menu is driven by
///   actions that the action layer already resolved from keys.
/// - It does not own the level path or the world height. Those are in
///   `engine/EngineConfig.hpp`, generated by CMake, and
///   [engine::scene::PlayScene] reads them.
///
/// ### Where the two frame-level guarantees are kept
///
/// A transition is applied at the start of a frame, never during one, and only the
/// active scene is updated or rendered. Both live in [engine::Application::update]
/// and [engine::Application::render] rather than here, because they are properties
/// of the frame loop and not of any one scene; this file cannot honour them and
/// cannot break them, which is the point.
#include "engine/Application.hpp"
#include "engine/scene/Scene.hpp"

#include <charconv>
#include <cstddef>
#include <cstdlib>
#include <exception>
#include <iostream>
#include <optional>
#include <string>
#include <string_view>
#include <system_error>

namespace
{

/// What the command line asked for.
///
/// Two flags and no more. `--frames` bounds the loop so a test can shut the game
/// down on its own, and `--keys` drives the keyboard from a recorded script so the
/// *shipped executable* can be made to play itself - which is the one thing a test
/// binary cannot do and the reason [engine::Application::runWithInput] exists.
struct RunOptions
{
    std::optional<std::size_t> frameLimit;
    std::string inputScript;
};

/// Reads `--frames <count>` and `--keys <script>`.
///
/// Both exist for the automated end-to-end runs, and a human will never type either.
/// What they are **not** is a way to change the game: `--keys` presses the same
/// physical keys the keyboard does, through the same [engine::input::Input], and the
/// same action layer resolves them, so a scripted run exercises the production path
/// rather than a shortcut around it.
///
/// ```text
///   --frames 300          run three hundred frames and stop
///   --keys "P D:60 ."     press P, hold D for sixty frames, advance one more
/// ```
[[nodiscard]] RunOptions parseRunOptions(const int argc, char* const argv[])
{
    constexpr std::string_view kFrameLimitFlag = "--frames";
    constexpr std::string_view kKeysFlag = "--keys";

    RunOptions options;

    for (int index = 1; index < argc; ++index)
    {
        const std::string_view argument{argv[index]};

        if (argument != kFrameLimitFlag && argument != kKeysFlag)
        {
            continue;
        }

        if (index + 1 >= argc)
        {
            throw std::invalid_argument{std::string{argument} + " requires a value"};
        }

        const std::string_view value{argv[++index]};

        if (argument == kFrameLimitFlag)
        {
            std::size_t frameCount = 0;
            const std::from_chars_result result =
                std::from_chars(value.data(), value.data() + value.size(), frameCount);

            if (result.ec != std::errc{} || result.ptr != value.data() + value.size() || frameCount == 0)
            {
                throw std::invalid_argument{"--frames expects a positive integer"};
            }

            options.frameLimit = frameCount;
            continue;
        }

        // The script's grammar belongs to [engine::Application::runWithInput],
        // which is the only thing that has to understand it. Duplicating the rules
        // here would be a second implementation of a rule with one implementation.
        options.inputScript.assign(value);
    }

    return options;
}

} // namespace

int main(const int argc, char* const argv[])
{
    try
    {
        const RunOptions options = parseRunOptions(argc, argv);

        engine::Application application;

        // The game starts at the menu, which is where the course says a game
        // starts: "The 'ESC' key should go 'back' to the Main Menu, or quit if on
        // the Main Menu" only means something if there is a Main Menu to go back
        // to.
        //
        // Recorded rather than performed - `changeScene` defers to the next frame
        // boundary - so the menu is not built until the first `update()`, by which
        // time the camera has been given its viewport and the window exists. The
        // menu's layout is computed from the camera's viewport, so building it
        // before the window was configured would lay it out against a zero-sized
        // view. That ordering is a consequence of the deferral and is why it is
        // documented here rather than left to be rediscovered.
        application.changeScene(engine::scene::SceneId::Menu);

        return application.runWithInput(options.inputScript, options.frameLimit);
    }
    catch (const std::exception& error)
    {
        // A level that will not load throws out of the transition inside
        // `Application::update`, which is inside `run`, and lands here. The message
        // is `what()`: `LevelParseError` and `LevelAssetError` both add the line
        // number the underlying problem was on, so this is a usable report rather
        // than a bare "error".
        std::cerr << "Fatal error: " << error.what() << '\n';
        return EXIT_FAILURE;
    }
}
